# Copyright (c) 2018-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2018-present Sven Greb <development@svengreb.de>
#
# Project:    styled-modern-normalize
# Repository: https://github.com/arcticicestudio/styled-modern-normalize
# License:    MIT
# References:
#   https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
dist: trusty
sudo: false
node_js:
  - "node"
os:
  - linux
before_install:
  - rm -rf ./node_modules
before_script:
  - npm install
script:
  - npm run lint
  - npm run dist
